### ISSUE TITLE
Mods with commented out init functions are incorrectly marked as outdated

### ISSUE THREAD

**Issue by blazeykat** [Steamopollys/Steamodded#100]
Commenting out your smods.init function, say instead of deleting it while porting a mod to 1.0, will cause it to report as outdated and prevent loading

**Comment by Aurelius7309** [comment]
I'll try to find a better solution, but the usage of SMODS.INIT is synactically the clearest change between 0.x and 1.x, so I currently can't think of a more reliable method to flag outdated mods. Please let me know if you think you know a better one.
