### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by EmilyV99** [Steamopollys/Steamodded#106]
![image](https://github.com/Steamopollys/Steamodded/assets/35015090/2af37514-b13f-43a0-a086-0ae1307b035e)

Both the classic and powershell downloads give this message, and do nothing else at all.

**Comment by Aurelius7309** [comment]
You should install Steamodded using Lovely instead.
1. Install Lovely by following the instructions [here](https://github.com/ethangreen-dev/lovely-injector)
2. Head to the [Release page](https://github.com/Steamopollys/Steamodded/releases) and select the latest release.
3. Within the `Assets` header, choose **Source code (zip)**.
4. Extract the downloaded zip file.
5. In your file explorer, navigate to Balatro's save directory: `%AppData%/Balatro`
6. Create a directory named `Mods` inside the save directory if it doesn't already exist, and navigate to it.
7. Move the interior `Steamodded-0.9.8` folder from the download into `Mods`. Make sure that you don't have two Steamodded folders inside each other: your file structure should not look like this (`Balatro/Mods/Steamodded-0.9.8/Steamodded-0.9.8/core/core.lua`), but like this (`Balatro/Mods/Steamodded-0.9.8/core/core.lua`).
