### ISSUE TITLE
main.lua (main function has more than 200 variables)

### ISSUE THREAD

**Issue by coolboy7D** [Steamopollys/Steamodded#109]
So, I try modding balatro (as you do) and no matter what mods i use i seem to keep getting the same error:
![image](https://github.com/Steamopollys/Steamodded/assets/170281011/b8fab282-5f2b-4589-b0dc-cf7c81749a75)
I used both the powershell and classic injectors and neither worked. Help!

**Comment by Aurelius7309** [comment]
It seems like you injected Steamodded multiple times. Verify your game files on Steam and reinstall Steamodded to fix. By the way, Lovely is a better way to install Steamodded that doesn't require re-injection. Install instructions can be found [here](https://github.com/Steamopollys/Steamodded/wiki/01.-Getting-started)
