### ISSUE TITLE
1.0.0 new localization system suggestion

### ISSUE THREAD

**Issue by ChromaPIE** [Steamopollys/Steamodded#115]
TL;DR: What it is now will still work, but allow an external language file(s) in its folder to take effect and have a higher priority.

Because, imagine a mod adding bunch of stuff with a community driven crowndin porject to support 5+ languages. The length of the Lua will be too disastrous to maintain the main code itself, all filled with loc texts.

A Minecraft mod can be a good example for dealing with multiple languages.

**Comment by Aurelius7309** [comment]
Added in https://github.com/Steamopollys/Steamodded/commit/ce3290d6cbf4c51c297dddef9bb60d9f6fca5bb7
