### ISSUE TITLE
Achievements Mod doesn't seem to work anymore on latest version

### ISSUE THREAD

**Issue by Jay2645** [Steamopollys/Steamodded#116]
I'm using Steamodded 1.0, and I've updated the Achievements Mod to the latest version in the examples directory and see it loaded successfully in the Mods menu.

On the latest version of Balatro, however, it seems I can't trigger any Steam Achievements. I've completed multiple challenge runs with some visual mods active, but the achievement doesn't seem to be triggering in Steam.

There was a moment where I had an outdated version of the Achievements Mod for a couple days without noticing; I'm not sure if that is relevant in any way.

My guess is that something changed in the latest version of Balatro regarding how it awards achievements? I'm not sure, that's just speculation.

**Comment by Jay2645** [comment]
Playing around with it a bit more -

With Steamodded disabled achievements worked fine. I triple-checked that the AchievementsEnabler.lua was up to date and confirmed that it was.

If I go into core.lua and locally flip the "achievements disabled" flag from true to false, I am able to get achievements (so it's an issue with Steamodded, nothing on Balatro's side).

My guess is that mods are being loaded out of order relative to `initGlobals()` _or_ `initGlobals()` is being called multiple times.

**Comment by Aurelius7309** [comment]
The issue seems to have been that `initGlobals()` was being called after mods are loaded, thus overriding any changes made to the achievements setting. This has been adjusted, so Achievements Enabler should now work properly again.
