### ISSUE TITLE
Error loading nativefs library! error using Steammodded 0.9.8 and Lovely 0.5.0-beta5

### ISSUE THREAD

**Issue by Pyrolaxian** [Steamopollys/Steamodded#119]
INFO - [♥] Lovely 0.5.0-beta5
INFO - [♥] Game directory is at "C:\\Users\\-\\Desktop\\Game Folders\\balatro"
INFO - [♥] Writing logs to "C:\\Users\\-\\AppData\\Roaming\\Balatro\\Mods\\lovely\\log"
INFO - [♥] Using mod directory at "C:\\Users\\-\\AppData\\Roaming\\Balatro\\Mods"
INFO - [♥] Cleaning up dumps directory at "C:\\Users\\-\\AppData\\Roaming\\Balatro\\Mods\\lovely\\dump"
INFO - [♥] Initialization complete in 11ms
INFO - [♥] Applied 1 patch to 'main.lua'
INFO - [♥] Applied 1 patch to 'game.lua'
INFO - [G] Failed to connect to the debug server
INFO - [G] 2024-06-03 14:50:22 :: DEBUG :: DebugConsole :: Steamodded Debug Socket started !
INFO - [G] 2024-06-03 14:50:22 :: ERROR :: Loader :: Error loading nativefs library!
INFO - [G] 2024-06-03 14:50:24 :: INFO  :: SpriteAPI :: All the sprites have been loaded!
INFO - [G] 2024-06-03 14:50:25 :: INFO  :: SpriteAPI :: All the sprites have been loaded!
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: StackTracePlus.lua
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: core.lua
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: deck.lua
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: joker.lua
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: planet.lua
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: r_blind.lua
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: seal.lua
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: sound.lua
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: spectral.lua
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: sprite.lua
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: suit.lua
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: tarot.lua
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: voucher.lua
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: debug.lua
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: loader.lua
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: game.lua
INFO - [G] 2024-06-03 14:50:25 :: TRACE :: Loader :: Skipping non-Lua file or invalid header: main.lua
INFO - [G] 2024-06-03 14:50:25 :: INFO  :: Loader :: 
INFO - [G] 2024-06-03 14:50:26 :: INFO  :: SpriteAPI :: All the sprites have been loaded!

Doesn't seem to impact gameplay, but should be required right?

**Comment by Aurelius7309** [comment]
NativeFS is not a required dependency of Steamodded, as long as you don't want to use a different Mods folder. This log actually shouldn't be classified as an error, but rather a warning.

**Comment by Pyrolaxian** [comment]
Hi,

Sorry, I should've been more specific

I'm trying to port mods to the mobile version that you can create with Balatro Mobile Maker. The premise is, if modFS is installed and functioning then it should allow the different directory of mod folder to load. I'm struggling to find a version of modFS that works on PC, nevermind mobile.
