### ISSUE TITLE
FiveOfAFlush Example mod doesn't work

### ISSUE THREAD

**Issue by PhoenixICE** [Steamopollys/Steamodded#12]
main.lua:1127: Bad Sprite type

Getting the above error when trying to load this mod for testing purposes

**Comment by PhoenixICE** [comment]
I think after trying to understand whats happening the spirte load code in the mod is wrong, i think it should be:
`local s_vulcan = SMODS.Sprite:new("fish", foaf_mod.path, "vulcan.png", 71, 95, "asset_images")`

Documentation is abit lacking around this tho

**Comment by Steamopollys** [comment]
Hello,

This mod was made during the Demo and is not maintained anymore. The referent Mod for Sprite testing is now the Negate Texture Pack.

The Sprite API have been changed a lot and this mod would need a large rewrite.

**Comment by PhoenixICE** [comment]
I see, the mod example should probably be deprecated then, is there a mod example for a new joker, I don't think I see one?

**Comment by Steamopollys** [comment]
Joker API is in Pre Release phase, it will be published after it goes live.
