### ISSUE TITLE
straight 

### ISSUE THREAD

**Issue by Thejelf** [Steamopollys/Steamodded#128]
straight does not work in the game

**Comment by Aurelius7309** [comment]
**"[X] does not work" is never enough information!**
- To have this question handled further please provide more information, and state the version of Steamodded you are using.

**Comment by Thejelf** [comment]
What can i see this informations??? I'm new and i dont know nothing about this sorry

**Comment by english5040** [comment]
It looks like you're just starting out. This isn't really the place you want- you'll be better off posting in modding-chat and modding-dev on the Discord where there are people who can chat about basics.
