### ISSUE TITLE
General improvement: Add more per-mod functions

### ISSUE THREAD

**Issue by english5040** [Steamopollys/Steamodded#146]
Similar to mod.set_debuff, we could have a lot more per-mod functions for common operations that currently require injection

**Comment by GauntletGames-2086** [comment]
Idea to pitch: Add all the blind related functions (debuff_hand, press_play, etc.). We did so for debuffing cards, so making other effects similar to blinds should also be made easier.

**Comment by WilsontheWolf** [comment]
Aure recently went and added a bunch of documentation so there's now a page for these mod releated functions. https://github.com/Steamopollys/Steamodded/wiki/Utility. I think for issues sake, it makes more sense to have issues that are more directed towards certain functionality that we should add, so I'll close it, and encourage anyone who wants specific methods to make an issue dedicated to those in particular.
