### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by PeanutAcoustics** [Steamopollys/Steamodded#17]
Please note that NamelessNanashi has explicitly denied you permission to utilize code from their repos and you are legally obligated to comply under the license or licenses utilized by aforementioned repos. This applies to all of their original code, including but not limited to shell scripts, actions, batch scripts, and other such utilities.

**Comment by Steamopollys** [comment]
Hello, this is part of a PR on their side so non of this can be extended to the code present on this repo.

The code will be replaced by a better solution over the time anyway.
