### ISSUE TITLE
Using the ALPHA version 1.0.0 crashes Balatro when scoring nil cards due to blind effect

### ISSUE THREAD

**Issue by seifer376** [Steamopollys/Steamodded#175]
When using only the Full Scoremod the issue does not exist. Crash only occurs when Steamodded is added back into the mix.

Oops! The game crashed:
functions/state_events.lua:861: attempt to index a nil value

Additional Context:
Balatro Version: 1.0.1f-FULL-SCOREMOD
Modded Version: 1.0.0-ALPHA-0708a-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta6
Steamodded Mods:

Stack Traceback
===============
(3) Lua field 'func' at file 'functions/state_events.lua:861'
Local variables:
 (*temporary) = nil
 (*temporary) = nil
 (*temporary) = string: "HUD_blind_debuff_1"
 (*temporary) = table: 0x1e3397e8  {pixellated_rect:table: 0x1e7859c8, click_offset:table: 0x1e01a198, children:table: 0x1e339810 (more...)}
 (*temporary) = string: "attempt to index a nil value"
(4) Lua method 'handle' at file 'engine/event.lua:99'
Local variables:
 self = table: 0x1f2f2d18  {start_timer:true, timer:TOTAL, blockable:true, trigger:immediate, func:function: 0x1f2f2cf8 (more...)}
 _results = table: 0x1e124628  {blocking:true, pause_skip:false, time_done:false, completed:false}
(5) Lua method 'update' at file 'engine/event.lua:182'
Local variables:
 self = table: 0x1e24cdd8  {queue_last_processed:12.533333333334, queues:table: 0x1e24ce00, queue_dt:0.016666666666667 (more...)}
 dt = number: 0.0167033
 forced = nil
 (for generator) = C function: next
 (for state) = table: 0x1e24ce00  {unlock:table: 0x1e24ce28, other:table: 0x1e24d2a0, tutorial:table: 0x1e24ce78 (more...)}
 (for control) = number: nan
 k = string: "base"
 v = table: 0x1e24ce50  {1:table: 0x1e1a83d8, 2:table: 0x1f2f2d18, 3:table: 0x1e5a78f8, 4:table: 0x1f2f2df0 (more...)}
 blocked = boolean: false
 i = number: 2
 results = table: 0x1e124628  {blocking:true, pause_skip:false, time_done:false, completed:false}
(6) Lua upvalue 'gameUpdateRef' at file 'game.lua:2484'
Local variables:
 self = table: 0x1dd03c70  {PALETTE:table: 0x1deeb0b8, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0.0167033
 http_resp = nil
(7) Lua method 'update' at file 'main.lua:496'
Local variables:
 self = table: 0x1dd03c70  {PALETTE:table: 0x1deeb0b8, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0.0167033
(8) Lua field 'update' at file 'main.lua:136'
Local variables:
 dt = number: 0.0167033
(9) Lua function '?' at file 'main.lua:78' (best guess)
(10) global C function 'xpcall'
(11) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 49 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by english5040** [comment]
This mod breaks server rules (redistributes Balatro), and we also cannot support such mods
