### ISSUE TITLE
Negative card implementation is incomplete, will conflict with vanilla behavior

### ISSUE THREAD

**Issue by english5040** [Steamopollys/Steamodded#177]
The play area has a limit of -28 cards in it (should be 5) after a run with Perkeo.

This may be a bug with the Negative edition's implementation in Steamodded

**Comment by english5040** [comment]
The above issue has been resolved, but there are still some things to do:
- CardArea:change_size() doesn't respect negative cards
- CardArea:change_size() sets real_card_limit which is supposed to keep track of your card_limit if it's negative; card_limit itself is set to 0. This may cause unexpected behaviors with negative cards

**Comment by Aurelius7309** [comment]
`CardArea:change_size()` not respecting negatives has been resolved by modifying `real_card_limit` when negative cards are drawn or removed. This seems to also resolve the other mentioned problem.
