### ISSUE TITLE
Discontinue unlicensed code utilization

### ISSUE THREAD

**Issue by PeanutAcoustics** [Steamopollys/Steamodded#18]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

              Hello, this is part of a PR on their side so non of this can be extended to the code present on this repo.

The code will be replaced by a better solution over the time anyway.

_Originally posted by @Steamopollys in https://github.com/Steamopollys/Steamodded/issues/17#issuecomment-1969376705_
            

Unfortunately, this cannot be hand-waved with an "I'll get to it later". While code adopts the destination license unless otherwise specified, said license still protects the original developer from behaviors exhibited here.

Their signed code is their code and they have asked you to remove it. Please remove said code immediately, as per the requests of the developer in accordance with the licensing of the files which they created and which you are no longer allowed to use.

The files in question to be deleted are as follows:
7-zip/7z-repack.zip
7-zip/7z-repack.zip.sig

This message is GPG-signed utilizing the same signature as the .sig to be removed.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEtABOyn9Qg31afmwft9dvrLFmXUAFAmXfaWQACgkQt9dvrLFm
XUA0Dg/9GV+5kMIyAa22YMe2oY2f7RPbNBTmakucyLodAvhgWfZsMIowP/ZMbrX/
RQTJlj+hSeApFe6yTOxpTLJPPZW1g/Bq6Ve/I2CfJd0TI1+CEv29d05gJ/zGWY0W
A6IYdC4VmEKXp/UPrkxeGP56H4Jaj/Tc9lezMYgozMAc3YRHspwb4RVZWu5HHOJE
tWoHhTdPS/s57P45iq4rY/8wd2OMPBfYMe7LRRmrDIxSepVISFhYnaRu9yrhdsL1
6X+7Qp88uVJDt7CGqXEJ5PGAeHDaSGYZZGdGmc7jLdUzEpbW1xVBgpKa/ToToCeX
DXwUrcX7LH1KEdGvXU2Bu89q15TWltIE3bUbferakXGYaplKBDFcncf5ivohyGDf
t7m66sfv29D3boEUc0kKgDjwN+5CMMJWcwwjna4ipMK5utUs1mIqA1bWOevH+ZYY
AJrEmYfO/trg0y0mBLfhny5n6IBLkeKQ97OHmkyFpQ6qfj1ew4yPJNalRKuAdJ1K
f1k8p2H5aeBbMjMAbJtLekTcQFcDv8GsTMQDWD+GayP0rnfCg5NhVnzHNznXC2IF
5q1cdae6EQfFhu3yWm1dI2La4LBnj6X5pp4evCmPMhTSR4flmzYl6RRcgxMss0OF
bWLoJj/Jyi0d0PCjx3hAf+Whtp9ef2zthwHdbamI040mn3LYFZ0=
=/gHS
-----END PGP SIGNATURE-----

**Comment by PeanutAcoustics** [comment]
Here's a version with optimized formatting for ease of verification, Github added a code block for some reason:

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Unfortunately, this cannot be hand-waved with an "I'll get to it later". While code adopts the destination license unless otherwise specified, said license still protects the original developer from behaviors exhibited here.

Their signed code is their code and they have asked you to remove it. Please remove said code immediately, as per the requests of the developer in accordance with the licensing of the files which they created and which you are no longer allowed to use.

The files in question to be deleted are as follows:
7-zip/7z-repack.zip
7-zip/7z-repack.zip.sig

This message is GPG-signed utilizing the same signature as the .sig to be removed.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEtABOyn9Qg31afmwft9dvrLFmXUAFAmXfaikACgkQt9dvrLFm
XUD9IQ//Vt8fCSKECV6K0pSK7plazigwAppeUAPInYxH5Cnb5pfdo3chWtPlTHXf
fj0mXfgrB9WC+u6/9uVKAScJ1WJJp11+/GlnPGEb0vc6r2VW4RCqdIXCux76++1S
cqLAQnVVXIvGo3939lLmYXUH4UCo2xfIuOjPKtYab/UZU9ghbZs31A3TH4gt9DYL
tDwD6wnbvJwEC4tMaG5jNEGd45MKNgTZdaswxmnPz/M2VDQoMRNyDTDKJWWtK1r/
YwH5w8+wxScJV71JUFXfeOaWM54W66+pxh0tU6pKC2Uax0WRPs4ik+6kR+TY+17o
u1BTz4Al3ZuMx5frIh0o1bjlM72EMBieUJQd9eSNKWt9i4tTgEUGImCc/9Db0hNV
860OW1s3rG2GmeSsmx5y4hDFVJ0RTrw7J8QzvWmHSbtVgZEMbEtgDx6tjmTI8mdy
ro7cbXP48yQcNt3CQXXRQ2YKdBjMouAJnfKKex/cG0X7t5KyqfiQUU24dX8lrn1S
AfpNjGxGZ9mPQQUgYyenxXwWt7/ukVN7EY4p+WlstKmfG/aiUwDD99iXOYw2Lsv5
fwVk+4shCpFDAvxpjtT5ga6NJZ8Y9VDkpfq57T5vKbbSIpSmFheXrt7aZX/WPtQ8
jAtHSY45MUyn831OQJl0nBfW0Ec4oWj68QniYN/5wa2Yvbj2VF0=
=bH22
-----END PGP SIGNATURE-----

**Comment by Steamopollys** [comment]
Like said before, since this is a PR coming directly from the author of the code, he don't have any right to ask for deletion.

However, I'm tired of this so I just resigned a new hand made repack.
