### ISSUE TITLE
Load order dependency

### ISSUE THREAD

**Issue by english5040** [Steamopollys/Steamodded#182]
Currently there is no way to declare that mod A depends on another mod B's code, such that mod A must be loaded after mod B; dependencies only check for existence.

(currently, as a workaround mod A can set a greater priority than mod B)

**Comment by Aurelius7309** [comment]
Holding off on this, priorities work well enough and this idea bends the limits of what's availiable at the time this information is collected. Being explicit with priority values is also more consistent for mods that want to load in a specific order without hard dependencies
