### ISSUE TITLE
Windows Defender (Win 11) flags steammodded_injector.exe as Trojan

### ISSUE THREAD

**Issue by ravikiranj** [Steamopollys/Steamodded#19]
Windows Defender (Win 11 - 22H2) immediately flags "steammodded_injector.exe" as "Trojan:Win32/Wacatac.H!ml" which is not obvious for a new user.

Worth adding a note to README.md and instructions to let Win11 trust the file to allow modding.

![Screenshot 2024-03-01 191412](https://github.com/Steamopollys/Steamodded/assets/389491/bdc6f4af-119a-4c5c-ad7a-aa7d35c48d94)

**Comment by Wipppp** [comment]
was about to post this. I am on WIN10 family 22H2 and it gets flagged as wacatac.h!ml.
For those worrying about it you can just run any other anti virus / anti malware app and it should not flag it. This is just microsoft and windows defender being weird and over protective. there is a LOT of false positive that windef flags as wacatac and other scary malware names.

**Comment by Steamopollys** [comment]
Hello, I'm actually working on a different solution!
