### ISSUE TITLE
Problems with lua_reload

### ISSUE THREAD

**Issue by Aurelius7309** [Steamopollys/Steamodded#190]
As it turns out, lua_reload is not made for reloading modules that modify globals. As such, hooks will be run multiple times after a soft reload. As it stands, we have to remove this module.
TODO:
- Is soft reloading achievable some different way? As of now I don't think it's feasible to do in code, but maybe Lovely can provide this functionality?
- Hard reloads on non-Mac systems are currently forced through Steam, but there may be a more direct way to do this. Potentially Lovely can also be of help here

**Comment by flakywanderer** [comment]
Love2d appears to have some functionality for hard restarting: https://www.love2d.org/wiki/love.event.restart
