### ISSUE TITLE
Potential security risk using this mod loader

### ISSUE THREAD

**Issue by sbordeyne** [Steamopollys/Steamodded#20]
You absolutely do not need the 7zip suite to decompress Balatro, as it's just a regular zip archive that you can decompress and extract using the python `ZipFile` API. Downloading a file off the internet without the user's consent is a big no-no for basic security reasons.

**Comment by woctezuma** [comment]
I don't know any alternative to 7zip which would repack the decompressed and modified archive into an executable file.

**Comment by sbordeyne** [comment]
Yes the balatro exe is just a zip archive with a different extension.

I do like the balamod project though, since it seems to be much more mature than any other project at this point (even my own)

**Comment by Steamopollys** [comment]
Hello, ZipFile can't correctly rebuild SFX zip with full integrity, it have already been tested.

**Comment by sbordeyne** [comment]
I did a bit more research around on the love documentation, and in barely 10 minutes, I found this python project (straight from the love2d wiki) which doesn't resort to using 7zip to pack the game. So your argument that no other pure python solution being viable does not stand. `zipfile` is perfectly able to pack love games into executables.

Here's the link : https://github.com/pfirsich/makelove (from the wiki here https://love2d.org/wiki/Game_Distribution )

Regardless, your loader still to this point represent a major security risk, and at the very least if you're not going to address the issue, you should put a very visible warning message at the top of the README of this repository.
