### ISSUE TITLE
latest nightly build gives error

### ISSUE THREAD

**Issue by Wipppp** [Steamopollys/Steamodded#21]
latest pre release works fine, the nightly right under does not. might be me though, not sure. (I tried to dl the nightly first)

![image](https://github.com/Steamopollys/Steamodded/assets/101094679/a193c94f-c9f7-4c18-ab2e-cb9ceffd8b08)

**Comment by Steamopollys** [comment]
Hello, Nightly build are currently broken, please use official Releases.
