### ISSUE TITLE
MacOS modding currently broken

### ISSUE THREAD

**Issue by IlyaTaidi** [Steamopollys/Steamodded#23]
The code seems to be written to only accept exe files. The resources directory in the .App format is different than what the code accepts

/Library/Application Support/Steam/steamapps/common/Balatro/Balatro.app/Contents/Resources

Balatro.love
GameIcon.icns
libsteam_api.dylib
license.txt
luasteam.so
OS X AppIcon.icns

I assume the .love file is what the code needs to be adjusted to accept, but I'm no lua dev, so if this could be fixed that would be incredible.

**Comment by Steamopollys** [comment]
Hello, the previous MacOS implementation was made to work with some kind of Wine wrapper. I will add a method for the official release in the next days.

**Comment by Steamopollys** [comment]
I will start taking a look to MacOS official release.

**Comment by ManveerBhullar** [comment]
Any workaround or fix for this?

**Comment by sbordeyne** [comment]
Use balamod, it comes with macos support already. You're more limited in your mod selection, but it's currently the only option for mac modding

**Comment by Woedenaz** [comment]
I managed to get it to work by getting the 7zip mac beta from here: https://7-zip.org/a/7z2402-mac.tar.xz
Moving the `7zz` file from there to `usr/local/bin` and making sure to restart the terminal afterwards.

I then went into `Balatro.app` and navigated to `Balatro.app/Contents/Resources`
In the terminal I navigated to git cloned `steamodded` folder and put `python3 steammodded_injector.py` and dragged the `Balatro.love` file into the terminal.

After hitting enter, the process appeared to work just fine with no errors. I had to make mac accept using the `7zz` executable in the security preferences but what else is new with having to force Macs to not treat the user like a baby. 

Only thing I'm unsure about now is _where_ I am supposed to put the `.lua` mod files. Appdata does not exist on Mac so I'm guessing the Application Support folder? I suppose that's the next step to figuring this out.

**Comment by MyNameIsJiji** [comment]
> I managed to get it to work by getting the 7zip mac beta from here: https://7-zip.org/a/7z2402-mac.tar.xz Moving the `7zz` file from there to `usr/local/bin` and making sure to restart the terminal afterwards.
> 
> I then went into `Balatro.app` and navigated to `Balatro.app/Contents/Resources` In the terminal I navigated to git cloned `steamodded` folder and put `python3 steammodded_injector.py` and dragged the `Balatro.love` file into the terminal.
> 
> After hitting enter, the process appeared to work just fine with no errors. I had to make mac accept using the `7zz` executable in the security preferences but what else is new with having to force Macs to not treat the user like a baby.
> 
> After that, you place the `.lua` mod files and any other required files in the `/Users/<username>/Library/Application Support/Balatro/Mods` folder!

This actually helped! Thank you so much!

**Comment by Steamopollys** [comment]
Ofc, feel free to do one and we will review it!

Btw, Lovely should be made compatible with MacOS in the next few days, it will help a lot to get Mac users to same injector standards than Windows ones.

**Comment by Billstar14** [comment]
> I managed to get it to work by getting the 7zip mac beta from here: https://7-zip.org/a/7z2402-mac.tar.xz Moving the `7zz` file from there to `usr/local/bin` and making sure to restart the terminal afterwards.
> 
> I then went into `Balatro.app` and navigated to `Balatro.app/Contents/Resources` In the terminal I navigated to git cloned `steamodded` folder and put `python3 steammodded_injector.py` and dragged the `Balatro.love` file into the terminal.
> 
> After hitting enter, the process appeared to work just fine with no errors. I had to make mac accept using the `7zz` executable in the security preferences but what else is new with having to force Macs to not treat the user like a baby.
> 
> After that, you place the `.lua` mod files and any other required files in the `/Users/<username>/Library/Application Support/Balatro/Mods` folder!

Hey. I've done what you said about downloading the 7zip beta and putting it into the usr/local/bin but when I try to run it on terminal I keep getting no such file or directory: '7zz'. Is there something specific that I missed or did I just followed the steps wrong like am I suppose to take only the 7zz.exe into usr/local/bin and not the whole file? Or is this a different issue?

**Comment by gsmoraes** [comment]
@Billstar14

Try one of the injectors I wrote:

https://github.com/Steamopollys/Steamodded/issues/23#issuecomment-2033283714

**Comment by Billstar14** [comment]
> @Billstar14
> 
> Try one of the injectors I wrote:
> 
> [#23 (comment)](https://github.com/Steamopollys/Steamodded/issues/23#issuecomment-2033283714)

Absolute Legend. It worked. Thanks so much
