### ISSUE TITLE
Cannot use `take_ownership` on seals

### ISSUE THREAD

**Issue by GauntletGames-2086** [Steamopollys/Steamodded#246]
e.x. if you try to do `SMODS.Seal:take_ownership("Red", {...})` it prints `Cannot take ownership of s_Red: Does not exist`, despite the fact that the key of Red Seal is "Red". 

Most likely fixed through adding `s_` to default seals.

**Comment by Aurelius7309** [comment]
Adding the class prefix to default seals probably causes more issues than it's worth, I suggest we remove the prefix altogether

**Comment by GauntletGames-2086** [comment]
Thing about it now, I agree.
