### ISSUE TITLE
Localization mod partially loaded when encountering prefix conflict

### ISSUE THREAD

**Issue by Dilant** [Steamopollys/Steamodded#248]
**UPDATE: please see the next post for the actual cause. Here is the original problem below.**

---

I'm writing a mod to **replace** the official Simplified Chinese (zh_CN) localization: 

```lua
SMODS.Language({
    key = "zh_CN",
    label = "简体中文",
    path = "zh_CN.lua",
    font = 2,
})
```

But when my localization string has **fewer lines** than the official one, **the redundant lines are not deleted**.

For example:

```lua
--- Official (3 lines)
j_scary_face = {
    name="恐怖面孔",
    text={
        "打出的{C:attention}人头牌{}",
        "在计分时",
        "给予{C:chips}+#1#{}筹码",
    },
}

--- Mine (2 lines)
j_scary_face = {
    name = "恐怖面孔",
    text = {
        "打出的每一张{C:attention}人头牌",
        "在计分时给予{C:chips}+#1#{}筹码",
    },
}

```

When I load my mod, **the third line is not removed**, which is not expected:

![image](https://github.com/user-attachments/assets/c8848c0a-4377-4be3-9563-9f654e5508b1)

You can reproduce this with my mod: https://github.com/Dilant/balatro-better-zh_CN

Thanks!

**Comment by Dilant** [comment]
I think I've found the cause.

I have two mods sharing the prefix `bett` (the other one is [Better Mouse and Gamepad](https://github.com/Kooluve/Better-Mouse-And-Gamepad) for steamodded 0.9.8), the other mod is successfully loaded, and my mod gets a `prefix conflict` warning message. After resolving the conflict (by deleting the other mod), my mod works well.

But why is it partially loaded, insteal of not being loaded at all?

**Comment by Aurelius7309** [comment]
There's two different issues at play here, for one localization files load regardless of if the mod itself loaded. The additional lines issue on the other hand is caused by me trying to merge these files too gracefully. Both of these issues have now been fixed
