### ISSUE TITLE
Gold Stake not being applied correctly

### ISSUE THREAD

**Issue by An1mate** [Steamopollys/Steamodded#251]
Had a Gold Stake run with Steamodded enabled, noticed that there were no Rental jokers. Replayed the seed in a completely vanilla game state (removed all modded files) and the rentals appeared as they should.

Had this happen on a fresh download of both Steamodded and the version.dll file needed.

**Comment by Jonathing** [comment]
Had this happen to me as well yesterday. I thought I had the streamer luck for a second not seeing any rentals.
