### ISSUE TITLE
game.lua:2673:  bad argument #1 to 'push'

### ISSUE THREAD

**Issue by Rizwanelansyah** [Steamopollys/Steamodded#262]
while making mod i get this error, after i read the error message, why the error is at file game.lua:2673 is this not my code error and why does the traceback point to Steamodded at file 'core/ui.lua:81', is this an error from Steamodded?
![20240914_07h49m19s_grim](https://github.com/user-attachments/assets/d09b19f7-01a6-415a-a7ef-12a330ab93f6)

**Comment by WilsontheWolf** [comment]
I'm not sure what the cause of this error is, and would probably need more context. Generally, it is best to get support in the [balatro discord](https://discord.gg/balatro)
