### ISSUE TITLE
Midas Mask and Pillar Boss Blind bug

### ISSUE THREAD

**Issue by An1mate** [Steamopollys/Steamodded#270]
If you play a face card against The Pillar with Midas Mask, the card will be incorrectly debuffed before scoring. Unsure if the face card being played in a previous ante/being turned to gold by Midas has anything to do with this (not played during the same ante whatsoever).

**Comment by Aurelius7309** [comment]
This and a related issue where copied cards were not being debuffed correctly by the Pillar have finally been fixed
