### ISSUE TITLE
Bug in Blinds collection

### ISSUE THREAD

**Issue by complex11011** [Steamopollys/Steamodded#272]
Mods loaded: Fusion Jokers, Galdur, Brainstorm, JenLib, Talisman, Nopeus, SDM_0's stuff, Cryptid, Incantation

Weird bug in the collection where the blinds section has an exclamation mark, but there is no way to remove it. The issue went away when I disabled Cryptid.

Last image is the collection without Cryptid enabled.

I was informed that this was likely a steamodded issue by the Cryptid author, so I've made an issue here.

![s_4](https://github.com/user-attachments/assets/ebfdcfae-9005-4e4d-9582-e46786a4622f)
![s_3](https://github.com/user-attachments/assets/932fdf16-f94a-47af-8734-31e86f1a5249)
![s_1](https://github.com/user-attachments/assets/7b003d5f-268c-4e6b-830a-915509030764)
![s_2](https://github.com/user-attachments/assets/d5631bbd-4b9a-42b4-92f4-5861e1f5eaf9)

**Comment by Aurelius7309** [comment]
I've been able to identify the root cause of the issue being that alerts for blinds not on the first page were not being displayed and thus never resolved from being unalerted. This is a simple oversight on my part, pushing a fix shortly
