### ISSUE TITLE
Achievement Enabler Not Working

### ISSUE THREAD

**Issue by complex11011** [Steamopollys/Steamodded#273]
Modlist:
- Achievements Enabler
- Aurinko
- Cryptid
- DebugPlus
- Fusion-Jokers
- Galdur
- Incantation
- Jen's Almanac
- JenLib
- Loop
- Nopeus
- SDM_0's stuff
- Steamodded
- Talisman

Achievement enabler is visibly loaded in the main menu, however no achievements seem to be triggering despite the conditions clearly being met (e.g. complete a run on red stake).

**Comment by complex11011** [comment]
I realised that this is due to the "unlock all" used in the profile selection screen, is there a way to enable achievements for a profile where "unlock all" has been used?

**Comment by Aurelius7309** [comment]
There's no plans to update the achievements enabler mod, however we might replace it with an in-game setting that could include achievements on unlocked profiles and seeded runs as an option
