### ISSUE TITLE
Can't lauch game with mod 

### ISSUE THREAD

**Issue by KyeaHz** [Steamopollys/Steamodded#277]
![Zrzut ekranu 2024-10-16 163927](https://github.com/user-attachments/assets/058f59f6-c4f2-411b-afc3-72732393dab0)
This thing pop up can someone help

**Comment by Aurelius7309** [comment]
You managed to install a severely deprecated version of Steamodded despite all warnings. Please install the newer version, as the mod you are trying to use requires it
