### ISSUE TITLE
initial test of modding the Mac App Store and Apple Arcade version ("Balatro+")

### ISSUE THREAD

**Issue by yozlet** [Steamopollys/Steamodded#278]
Just in case anyone else wants this: I couldn't find any info on how to get mods working with the new Apple port (meaning: the version which works across most Apple device OSes, using Game Center for player profile storage) so [I had a quick poke](https://github.com/ethangreen-dev/lovely-injector/issues/86). TL;DR: I found a couple of significant barriers, but maybe someone with more lua and/or macOS experience could bridge them?

**Comment by Aurelius7309** [comment]
Doesn't seem like there's been much progress on lovely's end. Even if lovely could support it, there would still be the problem that the arcade version's code has diverged significantly from the steam version, so it'd be near impossible to support both without a separate branch of the project. And even then, any other mods using lovely would still be unsupported unless they do the same. I also wouldn't even be able to test for that version and it just makes development more complicated if it were to happen. Watching for further progress but it seems there's nothing to do on our end
