### ISSUE TITLE
Modding not working

### ISSUE THREAD

**Issue by Low-Poly62** [Steamopollys/Steamodded#283]
I'm sorry if this is the wrong kind of question or if it even is an issue to ask as I'm new to modding games that don't have a modloader that functions. I'm trying to use 3 mods for Balatro those being Cryptid, Talisman, and Steammodded. Every time I launch Balatro it gives a command box which I assume is just the easier way to show that your mods are working and you are playing modded but it doesn't seem to work. I also have installed Lovely (or whatever its called) into balatro 

From the Videos I've watched after placing those mods into a folder in balatro appdata titled "Mods" it should apply the mods and a button should show up on the title saying mods. I look at the command box thing and it says this 

`INFO - Using mods directory at "C:\\Users\\lowpo\\AppData\\Roaming\\Balatro\\Mods"
Setting breakpad minidump AppID = 2379780
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561199459708776 [API loaded no]`

I have no idea what this means I assume the problem might be with Steammodded due to Steammodded being a API mod but if I'm wrong I'm really sorry. Thanks for helping if you can

**Comment by Aurelius7309** [comment]
Nothing seems wrong with that log message. Check your mods are actually in the location the message suggests and not elsewhere or nested inside other folders
