### ISSUE TITLE
I made a seamless "EZ" installer for steamodded + lovely injector

### ISSUE THREAD

**Issue by fosterbarnes** [Steamopollys/Steamodded#284]
not really an issue per se, but didn't know how else to reach out to the creators(s)

I've found a lot of people online confused or having issues with the process of installing steamodded and getting mods working, so I made a seamless, "EZ" installer called [steamoddedEZinstaller](https://github.com/fosterbarnes/steamoddedEZinstaller)

It works on windows with a one-liner in powershell, and linux (debian/ubuntu/steamOS etc.) with a one-liner in terminal. Just trying to spread the word for those that are having issues

**Comment by Aurelius7309** [comment]
Thanks for making this, but it's not the type of script I'd want to give official recognition on the repo. Esp with there being an external mod manager in development that would replace the entirety of the functionality this has. Feel free to reach out to me on Discord if you want to discuss this, for now I'm closing this as there's no "issue" here
