### ISSUE TITLE
Add hidden option to cards

### ISSUE THREAD

**Issue by DigitalDetective47** [Steamopollys/Steamodded#296]
Allow cards to be completely hidden from the collection.
Could be useful for things like tags that create booster packs with specific contents, such as cryptid's empowered tag to make it appear like a normal booster pack

**Comment by DigitalDetective47** [comment]
still counts when displaying the number of cards in the main collection screen

**Comment by DigitalDetective47** [comment]
can also create an undismissable notification in the collection

**Comment by Aurelius7309** [comment]
Oops, I forgot about that. Will fix

**Comment by Aurelius7309** [comment]
Done
