### ISSUE TITLE
Consumables with eternal stickers

### ISSUE THREAD

**Issue by Cheesy-Brik** [Steamopollys/Steamodded#313]
Consumables are compatible with eternal stickers but using Card:set_eternal(true) doesn't work, instead you have to set it directly with Card.ability.eternal = true. Since it's mostly compatible by default I think using the set_eternal func should work as it's safer than setting the value directly.

**Comment by GauntletGames-2086** [comment]
This is a flaw with the vanilla implementation of Eternal. The vanilla function requires the card center to have `eternal_compat` in it's config, which is only present for jokers and no other card types. 
Steamodded does not use nor suggests using this function as all stickers have been re-implemented to use SMODS.Sticker API for `take_ownership` purposes. 
For applying an eternal sticker onto a card, use `SMODS.Stickers["eternal"]:should_apply(card, center)` (if you want to check for compat and RNG) or `SMODS.Stickers["eternal"]:apply(card, true)` (if you don't care for eternal_compat or RNG checks).

**Comment by GauntletGames-2086** [comment]
Forgot, `should_apply` just returns true/false, `apply` would need to be used anyways xdd
