### ISSUE TITLE
The mod causes the game to crash with an error

### ISSUE THREAD

**Issue by LianLiYi** [Steamopollys/Steamodded#318]
Oops! The game crashed:
card.lua:4985: attempt to call field 'add_suit_mult' (a nil value)

Additional Context:
Balatro Version: 1.0.1g-FULL
Modded Version: 1.0.0~ALPHA-1203b-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.6.0
Steamodded Mods:
Lovely Mods:
    1: DVPreview
    2: DVSimulate

Stack Traceback
===============
(3) Lua local 'joker_simulation_function' at file 'card.lua:4985'
Local variables:
 joker_obj = table: 0x0c017c60  {id:wrathful_joker, debuff:false, rarity:1, ability:table: 0x0c017d78}
 context = table: 0x0bd395b8  {before:true, scoring_name:High Card, scoring_hand:table: 0x0c425be8, full_hand:table: 0x0c272eb0 (more...)}
 (*temporary) = nil
 (*temporary) = table: 0x0c017c60  {id:wrathful_joker, debuff:false, rarity:1, ability:table: 0x0c017d78}
 (*temporary) = table: 0x0bd395b8  {before:true, scoring_name:High Card, scoring_hand:table: 0x0c425be8, full_hand:table: 0x0c272eb0 (more...)}
 (*temporary) = string: "attempt to call field 'add_suit_mult' (a nil value)"
(4) Lua field 'simulate_joker' at file 'functions/common_events.lua:3389'
Local variables:
 joker_obj = table: 0x0c017c60  {id:wrathful_joker, debuff:false, rarity:1, ability:table: 0x0c017d78}
 context = table: 0x0bd395b8  {before:true, scoring_name:High Card, scoring_hand:table: 0x0c425be8, full_hand:table: 0x0c272eb0 (more...)}
 joker_simulation_function = Lua function '?' (defined at line 4984 of chunk card.lua)
(5) Lua field 'simulate_joker_before_effects' at file 'functions/common_events.lua:3197'
Local variables:
 (for generator) = C function: builtin#6
 (for state) = table: 0x0c4962c8  {1:table: 0x0c4962f0, 2:table: 0x0c017c60, 3:table: 0x0c017e00, 4:table: 0x0c338430 (more...)}
 (for control) = number: 2
 _ = number: 2
 joker = table: 0x0c017c60  {id:wrathful_joker, debuff:false, rarity:1, ability:table: 0x0c017d78}
(6) Lua field 'simulate' at file 'functions/common_events.lua:2985'
Local variables:
 null_ret = table: 0x0c0a3fc0  {dollars:table: 0x0c38e748, score:table: 0x0c38e6b8}
(7) Lua field 'func' at file 'main.lua:1340'
Local variables:
 (*temporary) = table: 0x0b910e38  {joker_order:table: 0x0c05a2d0, is_enough_to_win:function: 0x0bb549b8, get_score_node:function: 0x0b90cdd8 (more...)}
(8) Lua method 'handle' at file 'engine/event.lua:99'
Local variables:
 self = table: 0x0bf112e8  {start_timer:true, timer:TOTAL, blockable:true, trigger:immediate, func:function: 0x0c454ce0 (more...)}
 _results = table: 0x0bb45b70  {blocking:true, pause_skip:false, time_done:false, completed:false}
(9) Lua method 'update' at file 'engine/event.lua:182'
Local variables:
 self = table: 0x0bf0c1b8  {queue_last_processed:72.183333333331, queues:table: 0x0bf0c1e0, queue_dt:0.016666666666667 (more...)}
 dt = number: 0.00699707
 forced = nil
 (for generator) = C function: next
 (for state) = table: 0x0bf0c1e0  {unlock:table: 0x0bf0c208, other:table: 0x0bf0c680, tutorial:table: 0x0bf0c258 (more...)}
 (for control) = number: nan
 k = string: "base"
 v = table: 0x0bf0c230  {1:table: 0x0bce3828, 2:table: 0x0bf112e8}
 blocked = boolean: false
 i = number: 2
 results = table: 0x0bb45b70  {blocking:true, pause_skip:false, time_done:false, completed:false}
(10) Lua upvalue 'gameUpdateRef' at file 'game.lua:2494'
Local variables:
 self = table: 0x0b8e4a88  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x0c330130 (more...)}
 dt = number: 0.00699707
 http_resp = nil
(11) Lua method 'update' at Steamodded file 'core/ui.lua:81' 
Local variables:
 self = table: 0x0b8e4a88  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x0c330130 (more...)}
 dt = number: 0.00699707
(12) Lua field 'update' at file 'main.lua:965'
Local variables:
 dt = number: 0.00699707
(13) Lua function '?' at file 'main.lua:909' (best guess)
(14) global C function 'xpcall'
(15) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 880 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by Cheesy-Brik** [comment]
You should close this issue here and post the issue on the mod's repo

**Comment by Aurelius7309** [comment]
Closing as this is not an issue with Steamodded
