### ISSUE TITLE
Critical Issue with .json files

### ISSUE THREAD

**Issue by Cheesy-Brik** [Steamopollys/Steamodded#322]
PR #315 completely changed the versioning syntax with no documentation, should add that.

**Comment by WilsontheWolf** [comment]
Yeah that should probably be documented. For now the big change is the dependencies and related fields. They now look something like:
```json
[
"steamodded (>=1.0.0~) (<<2.0.0)",
"talisman (== 2.0.0)"
]
```

**Comment by Aurelius7309** [comment]
Docs updated to reflect the change
