### ISSUE TITLE
Consumable types don't append mod prefix

### ISSUE THREAD

**Issue by DigitalDetective47** [Steamopollys/Steamodded#323]
could cause name conflicts

**Comment by DigitalDetective47** [comment]
example:
```lua
SMODS.ConsumableType({
    key = "index",
    primary_colour = HEX("FFFFFF"),
    secondary_colour = HEX("FF0000"),
    shop_rate = 4,
    loc_txt = {},
})
```
referencing this with `SMODS.create_card` has to be set as `set = "index"` instead of `set = "modid_index"`

**Comment by Aurelius7309** [comment]
The way it's handled currently is consistent with not having to specify mod prefixes in other places. The potential for overlap in a rather small collection like consumable types isn't large enough to warrant a change like this reflecting badly on dev experience. Note that you would also have to include the prefix each time when creating a consumable of your type. Also it would be a huge breaking change that would require immediate reaction from the creators of several mods for no particular reason.
