### ISSUE TITLE
Organise directories better

### ISSUE THREAD

**Issue by DivvyCr** [Steamopollys/Steamodded#325]
The current organisation of this repository seems extremely unintuitive and messy. It would be a great opportunity to fix it with the next big release (the Beta, I believe?).

My suggestion is to simply reorganise files and directories in a more standard way:

```
.github/
assets/
libs/
 ├─ json/
 ├─ nativefs/
 ├─ debug/
lovely/
src/
 ├─ Current contents of core/ directory
 ├─ loader.lua
```

(Files like `config.lua` and `test.lua` should ideally be moved into one of the directories, too.)

I understand that this would affect Lovely configurations. If you agree to this suggestion, I will happily adjust all Lovely patches myself, ensuring that Steamodded still loads as expected. This should be a simple change, unless I'm missing something.

**Comment by DivvyCr** [comment]
The example mods directory I would move out into a separate repository. There is no real reason for it to be in the source files, when it can be linked in the README for any curious mod developers.

**Comment by WilsontheWolf** [comment]
This is probably a good idea, though probably need some more feedback on whether or not we want to do this from some of the other maintainers. Just some thoughts, test.lua was for testing and shouldn't have been kept around so I deleted it. Also debug doesn't really make sense as a lib as it is part of SMODS and not some dep, and also doesn't have lua code. Config.Lua also needs to stay where it is as it has special meaning (SMODS treats files called config.Lua in the root directory as the default for config).

**Comment by Aurelius7309** [comment]
I'd go for something like this. Anything y'all think needs changing?

**Comment by DivvyCr** [comment]
I still wonder if the Python debug file better fits into `libs` because it's a (custom) external/non-Lua tool.

Ultimately up to you all, obviously.
