### ISSUE TITLE
Missing Button to Redirect to "Mods" Folder After Adding Mods

### ISSUE THREAD

**Issue by pablobn** [Steamopollys/Steamodded#326]
When the "mods" folder is empty, the game automatically provides a button that redirects you to that folder. However, once you add one or more mods to the folder, this button disappears, and you are required to locate the "mods" folder manually. This can be inconvenient for users who frequently manage or update their mods.

**Comment by Aurelius7309** [comment]
Added in https://github.com/Steamopollys/Steamodded/commit/c88333bb4db876dc3c1102fcbf4d93db859739e3
