### ISSUE TITLE
The Wheel blind's description has duplicated text

### ISSUE THREAD

**Issue by jumbocarrot0** [Steamopollys/Steamodded#337]
Upon opening The Wheel in the collection, its description looks like this:

![image](https://github.com/user-attachments/assets/a6a49d6a-1f9c-4a22-80e4-adedbda0e150)

Switching profiles will add additional nil's (I imagine this is something to do with reloading the game data somehow)

![image](https://github.com/user-attachments/assets/9e4ee2ae-8921-4db9-a217-a47ca463349f)

I have disabled all mods and the issue still persists. It only goes away when I disable steammodded enitrely.

I initially encountered this during a game, where The Wheel's description during blind selection was "11 in 7 cards get drawn face down" but it had no gameplay effect, so presumably it was the number '1' duplicated. However, I cannot repeat this issue when testing with the debug menu.

None of the other blinds have this issue, nor do any probability-based jokers.

**Comment by jumbocarrot0** [comment]
My guess is that it would have something to do with this line
![image](https://github.com/user-attachments/assets/e12d4324-ea58-45bc-88ca-f4630cf71f1f)

If this were triggering multiple times upon the game loading without resetting to the original localization text, then it would cause multiple '#1#'s to be added, causing this issue.

**Comment by Aurelius7309** [comment]
This was a combination of the process_loc_text function having repeated calls, there being a special case for The Wheel in the collection that was never removed, and the lack of a `collection_loc_vars` function. All is resolved now, this must have been overlooked when fixing the blind's text in all the other places
