### ISSUE TITLE
Make a Context class

### ISSUE THREAD

**Issue by Cheesy-Brik** [Steamopollys/Steamodded#340]
Currently context's have varying structures throughout the game, the prime example is deck context's vs joker context's. We should use one unified object type so that it's guaranteed the context object is structured the same. 

I know this is a pretty breaking change so feel free to reject it but I think it would be beneficial for the overall usability of the context system.

**Comment by Aurelius7309** [comment]
I don't think this could be made compatible with vanilla contexts at all? Besides context is just argument that gives information from where the function was called from, naturally this varies depending on what's being done
