### ISSUE TITLE
injector.py seems to be missing therefore can to mod with wine.

### ISSUE THREAD

**Issue by RakibRyan** [Steamopollys/Steamodded#342]
![Screenshot From 2024-12-21 00-10-04](https://github.com/user-attachments/assets/29e58f4c-d2af-40ea-a483-fff0982f0abe)

```
python3 steamodded_injector.py $($HOME/.local/share/Steam/steamapps/common/Balatro/Balatro.exe | head -n 1) $HOME/.local/share/Steam/steamapps/common/Balatro/Balatro.exe
bash: /home/rakibryan/.local/share/Steam/steamapps/common/Balatro/Balatro.exe: Permission denied
python3: can't open file '/home/rakibryan/apps/Steamodded-main/steamodded_injector.py': [Errno 2] No such file or directory
```

**Comment by WilsontheWolf** [comment]
The injector is no longer supported. You can follow the instructions at https://github.com/Steamopollys/Steamodded/wiki for the new instructions, (there's an additional env variable option you have to do for lovely with wine, but after that it should work just fine). 

If for some reason you have to use the old injecgor, you can updare the links in the source to point to the 0.9.8 branch, or i think the exe in the release still works
