### ISSUE TITLE
[Idea] Leveraging Balatro's `.jkr` files

### ISSUE THREAD

**Issue by nskobelevs** [Steamopollys/Steamodded#344]
Came across this repo in my process of exploring Balatro's code and seeing what mod loaders are available.

While skimming through Balatro I did notice it has an _interesting_ way of persisting data. I specifically looked at the `settings.jkr` file but I imagine the same is true for the profile files as well.

These files are just deflate compresses Lua source code files that are loaded by the game, decompressed and executed as Lua code to get the stored data.

One could inject arbitrary code into these to run when the game fetches the settings during start up.

Just throwing this out here (if it wasn't known already) in case it might be useful in some way. Not sure about the actual utility here over lovely injector given at that point the code is already loaded into the process and I don't know what kind of patching can be done but might have some uses.

<details>
<summary> Sample injector script</summary>

**Usage:** `lua injector.lua <original settings.jkr path> <path to code to inject> <output path>`

```lua
LibDeflate = require("LibDeflate")

local function read_file(path)
    local f = assert(io.open(path, "rb"))
    local content = f:read("*all")
    f:close()
    return content
end

local function save_file(contents, path)
    local file, err = io.open(path, 'wb')
    if file then
        file:write(contents)
        file:close()
    else
        print("error:", err)
    end
end

local compressed_data = read_file(arg[1])
local original = LibDeflate:DecompressDeflate(compressed_data)

local mixin = read_file(arg[2])

local output = mixin .. "\n" .. original

local recompressed_data = LibDeflate:CompressDeflate(output)

save_file(recompressed_data, arg[3])
```

</details>

**Comment by Aurelius7309** [comment]
This works and could be used in more limited environments to make a basic mod loader, but it doesn't compare to Lovely whatsoever. Lovely is absolutely needed for Steamodded to function at this point, so it's not really of use here.
