### ISSUE TITLE
Can you make a build of latest steamodded without lovely 

### ISSUE THREAD

**Issue by DracyanZeutron** [Steamopollys/Steamodded#347]
Current steamodded build is old but compatible with balatro mobile maker allowing us to add mods but with version 1.0.0 alpha using lovely makes it so that we cannot use it mobile so is it possible to make a build of steamooded latest version

**Comment by Aurelius7309** [comment]
It's possible to modify the source code directly in a way where Steamodded would be partially injected by replacing files with Lovely dumps. However this wouldn't be of much use as a lot of currently up-to-date mods use lovely patches themselves and you'd have to make a new staří build each time you're adding, removing or updating any mods that use lovely. There's probably some potential to make Lovely work on mobile though

**Comment by DracyanZeutron** [comment]
Please can you make it because the mods i want to use only use steamodded

**Comment by Aurelius7309** [comment]
You'd have to do this yourself, I'm not making a legacy injector-type program that would do this for you due to the dependency on lovely and I can't send patched executables around for obvious reasons.

**Comment by Aurelius7309** [comment]
You're basically asking me to remove the lowest-level dependency we have... A lot of what made 0.9.8 so unmaintainable and necessitating its replacement was that it does not use Lovely.
