### ISSUE TITLE
Game crashes when starting playing

### ISSUE THREAD

**Issue by raychen1217** [Steamopollys/Steamodded#350]
I am sure that I install the latest version of both Lovely and Steamodded, but this is the error message I get when try to play the game, the game didn't crash immediately when I launch the game, but crashed after I clicked play. How can I fix it?

`Oops! The game crashed:
functions/UI_definitions.lua:1616: attempt to index global 'self' (a nil value)

Additional Context:
Balatro Version: 1.0.1n-FULL
Modded Version: 1.0.0~ALPHA-1224d-STEAMODDED
LÖVE Version: 11.5.0
Lovely Version: 0.6.0
Steamodded Mods:
Lovely Mods:

Stack Traceback
===============
(3) Lua global 'create_UIBox_blind_choice' at file 'functions/UI_definitions.lua:1616'
Local variables:
 type = string: "Small"
 run_info = nil
 disabled = boolean: false
 blind_choice = table: 0x350ceae0  {animation:table: 0x350b2260, config:table: 0x3532b3b0}
 extras = table: 0x3508c128  {nodes:table: 0x350f6ba8, n:4, config:table: 0x3502a830}
 stake_sprite = table: 0x34e87b00  {click_offset:table: 0x34fe3810, children:table: 0x34fe2768, sprite_pos:table: 0x353a5360 (more...)}
 (*temporary) = table: 0x3504e250  {type:raw_descriptions, set:Blind}
 (*temporary) = nil
 (*temporary) = nil
 (*temporary) = table: 0x35086ee0  {tally:0, triggered:false, pos:table: 0x35329790, tag_sprite:table: 0x34fbe038 (more...)}
 (*temporary) = table: 0x351a6948  {nodes:table: 0x351a8398, n:3, config:table: 0x34cd0830}
 (*temporary) = table: 0x34fbe038  {float:true, click_offset:table: 0x35085570, children:table: 0x3516e7d0 (more...)}
 (*temporary) = table: 0x3508c128  {nodes:table: 0x350f6ba8, n:4, config:table: 0x3502a830}
 (*temporary) = table: 0x350f6ba8  {1:table: 0x3502a590, 2:table: 0x35194040}
 (*temporary) = table: 0x35194040  {nodes:table: 0x35363a98, n:4, config:table: 0x35193f90}
 (*temporary) = table: 0x35363a98  {1:table: 0x34dcd0c0, 2:table: 0x350cde48}
 (*temporary) = table: 0x350cde48  {nodes:table: 0x34f97610, n:3, config:table: 0x350890f0}
 (*temporary) = table: 0x34f97610  {1:table: 0x35327538}
 (*temporary) = table: 0x35327538  {config:table: 0x3516e5f0, n:1}
 (*temporary) = table: 0x3516e5f0  {colour:table: 0x34de6d20, scale:0.4, text:Skip Blind}
 (*temporary) = table: 0x34de6d20  {1:0.53333333333333, 2:0.53333333333333, 3:0.53333333333333, 4:0.6}
 (*temporary) = string: "b_skip_blind"
 (*temporary) = nil
 (*temporary) = string: "Skip Blind"
 (*temporary) = string: "b_skip_blind"
 (*temporary) = nil
 (*temporary) = nil
 (*temporary) = table: 0x3505d7a0  {1:table: 0x34da35b0, 2:table: 0x3502a430}
 (*temporary) = number: 2
 (*temporary) = number: -0.24
 (*temporary) = number: 2
 (*temporary) = table: 0x34da35b0  {k:1, v:0.24}
 (*temporary) = table: 0x3502a430  {k:2, v:-0.24}
 (*temporary) = boolean: false
 (*temporary) = string: "attempt to index global 'self' (a nil value)"
(4) Lua global 'create_UIBox_blind_select' at file 'functions/UI_definitions.lua:1519'
Local variables:
 width = number: 12.2927
 (*temporary) = table: 0x350473a8  {}
 (*temporary) = table: 0x34e282d8  {remove_group:function: 0x34e11a58, draw:function: 0x34e11ad8, print_topology:function: 0x34de9188 (more...)}
 (*temporary) = table: 0x350c9598  {}
 (*temporary) = table: 0x350c94e8  {n:7, config:table: 0x350c9798}
 (*temporary) = table: 0x350df7b0  {}
 (*temporary) = Lua function '?' (defined at line 6251 of chunk functions/UI_definitions.lua)
 (*temporary) = table: 0x352972f0  {}
(5) Lua field 'func' at file 'game.lua:3301'
Local variables:
 (*temporary) = table: 0x34dddbd8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x35792058 (more...)}
 (*temporary) = table: 0x34e282d8  {remove_group:function: 0x34e11a58, draw:function: 0x34e11ad8, print_topology:function: 0x34de9188 (more...)}
 (*temporary) = table: 0x34f76b78  {}
(6) Lua method 'handle' at file 'engine/event.lua:99'
Local variables:
 self = table: 0x34fff438  {start_timer:true, timer:TOTAL, blockable:true, trigger:immediate, func:function: 0x34fafb30 (more...)}
 _results = table: 0x34ff0ca8  {blocking:true, pause_skip:false, time_done:false, completed:false}
(7) Lua method 'update' at file 'engine/event.lua:182'
Local variables:
 self = table: 0x353a2720  {queue_last_processed:7.3666666666666, queues:table: 0x353a2748, queue_dt:0.016666666666667 (more...)}
 dt = number: 0.0166543
 forced = nil
 (for generator) = C function: next
 (for state) = table: 0x353a2748  {unlock:table: 0x353a2770, other:table: 0x353a2be8, tutorial:table: 0x353a27c0 (more...)}
 (for control) = number: nan
 k = string: "base"
 v = table: 0x353a2798  {1:table: 0x35130fd0, 2:table: 0x3540e7f8, 3:table: 0x34fff438, 4:table: 0x34f76b28 (more...)}
 blocked = boolean: false
 i = number: 3
 results = table: 0x34ff0ca8  {blocking:true, pause_skip:false, time_done:false, completed:false}
(8) Lua upvalue 'gameUpdateRef' at file 'game.lua:2519'
Local variables:
 self = table: 0x34dddbd8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x35792058 (more...)}
 dt = number: 0.0166543
 http_resp = nil
(9) Lua method 'update' at Steamodded file 'src/ui.lua:81' 
Local variables:
 self = table: 0x34dddbd8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x35792058 (more...)}
 dt = number: 0.0166543
(10) Lua field 'update' at file 'main.lua:992'
Local variables:
 dt = number: 0.0166543
(11) Lua function '?' at file 'main.lua:931' (best guess)
(12) global C function 'xpcall'
(13) LÖVE function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 902 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(LÖVE Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(LÖVE Function)' (defined at line 355 of chunk [love "boot.lua"])
`

**Comment by raychen1217** [comment]
I rolled back to commit "77bf5e24f3a221244f222ce301abd94c8e8bafef", and the bug is gone.

**Comment by Eremel** [comment]
Fixed in v1224e
