### ISSUE TITLE
Quick restarting prevents the game from saving profile/run data

### ISSUE THREAD

**Issue by Aurelius7309** [Steamopollys/Steamodded#351]
After having held 'm' to quick restart game, I played two full runs yesterday without any successful save of my run to save.jkr. Need to investigate why this happens

**Comment by Aurelius7309** [comment]
Moved: https://github.com/MathIsFun0/Talisman/issues/28

**Comment by MathIsFun0** [comment]
Fixed this one on Talisman's side now.
