### ISSUE TITLE
Custom booster packs crash when opened during a blind

### ISSUE THREAD

**Issue by jumbocarrot0** [Steamopollys/Steamodded#354]
A rather obscure bug, since this doesn't happen during vanilla gameplay. Doubly odd is that the vanilla booster packs do not crash when opened during a blind. However, I think I found the cause.

The update_pack function starts with this line:
`if G.buttons then self.buttons:remove(); G.buttons = nil end`

This line I think would only trigger when a pack is opened during a blind, since from what I saw `G.buttons` refers to the 'Play Hand' and 'Discard' buttons that appear during a blind. When it does so however, it will try to reference `self.buttons`, which doesn't seem to exist, causing a crash.

From limited testing, changing this to `if G.buttons then G.buttons:remove(); G.buttons = nil end` seems to fix the problem, and matches the function of the vanilla booster packs.

**Comment by GauntletGames-2086** [comment]
Good catch, just fixed it.
