### ISSUE TITLE
Adding custom sounds to the game

### ISSUE THREAD

**Issue by G3Kappa** [Steamopollys/Steamodded#36]
While custom textures are supported, custom sounds are not.

The `play_sound` function will always look for sounds in `resources/sounds` relative to the game's root path. Therefore, even if you specify an absolute path, `play_sounds` will not be able to see that file.

I suppose that a possible solution to this problem would be to copy the sound files from the mod's folder to the game's folder on startup.

**Comment by Steamopollys** [comment]
Hey,

I will add this to the list of future improvements.

**Comment by Aurelius7309** [comment]
This feature has been introduced in version 0.9.
