### ISSUE TITLE
I cant get any mods to work

### ISSUE THREAD

**Issue by Zaphrom** [Steamopollys/Steamodded#363]
No matter if they are in single form, a folder or in a ZIP file I cant get any mods for Balatro to work with my steammodded.
![Screenshot 2024-12-29 164122](https://github.com/user-attachments/assets/d56495a9-12f2-46fa-83a5-8c8ff1db2654)

**Comment by Aurelius7309** [comment]
- You have installed Steamodded 0.9.8, despite all warnings that it's deprecated. Verify game files on Steam to uninstall this old version and follow [these instructions](https://github.com/Steamopollys/Steamodded/wiki) to install the newest version.
- Each mod should be in its own folder (not zip file) and shouldn't have nested folders.

**Comment by Zaphrom** [comment]
After installing lovely and adding the mod folder that I want to play while installing steammodded-main into my mods folder it still doesnt work.
![Screenshot 2024-12-29 182531](https://github.com/user-attachments/assets/115c0fe7-1598-47a1-96e0-1e9c48d63ab0)

**Comment by Aurelius7309** [comment]
Can I see your game installation folder? That looks like either lovely isn't installed correctly, or your mod folders are nested
