### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by achar45** [Steamopollys/Steamodded#40]
Your mods make balatro better and way more fun! Wanted to say thank you!

I have a request also. Do you think it's possible to make a mod that buffs the probability of getting a soul card for legendary jokers? Getting the completionist++ achievement is almost impossible or takes like 20 hours of resetting runs. Plus I think it's fun to have them not be so rare.

**Comment by Steamopollys** [comment]
Hey! I think you should ask for it on Balatro official Discord, a bunch of mod dev would be really happy to do it for you!
