### ISSUE TITLE
On Linux script fails to unzip

### ISSUE THREAD

**Issue by deafwired** [Steamopollys/Steamodded#46]
When i am running the python script on arch, it run into the error, 
```
Traceback (most recent call last):
  File "/home/matt/Steamodded/steamodded_injector.py", line 178, in <module>
    subprocess.run([command, "x", f"-o{temp_dir.name}", sfx_archive_path], check=True)
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '7zz'
```
I'm not completely familiar with 7-zip, but I believe that the commandline name is 7z, when i replaced 7zz with 7z it unzipped properly and completed.
I'm also assuming its the same on mac.

**Comment by Steamopollys** [comment]
Hello, that's the first time I see this error for Linux. What distro are you using ? Are you using the same command than the one provided in the Readme ?

**Comment by deafwired** [comment]
I'm on arch linux, i ran the command in the readme (`git clone https://github.com/Steamopollys/Steamodded.git && cd Steamodded && python3 steamodded_injector.py $($HOME/.local/share/Steam/steamapps/common/Balatro/Balatro.exe | head -n 1) $HOME/.local/share/Steam/steamapps/common/Balatro/Balatro.exe`) but got that error from the steamodded_injector.py. I changed 7zz on line 155 to 7z and it worked properly. 
I do have 7-zip installed on my distro.
![image](https://github.com/Steamopollys/Steamodded/assets/37221707/9c518329-f898-40fe-8256-34c034760c01)

**Comment by Steamopollys** [comment]
That's odd, this part was made specially to help Mac and Linux users to run 7zip. What package are you using ? [p7zip](https://github.com/p7zip-project/p7zip) or maybe an other ?

**Comment by deafwired** [comment]
It seems to be p7zip

**Comment by NathanFrasier** [comment]
I had the exact same issue, and the exact same fix worked for me as well. I'm using Debian Unstable

**Comment by Wffv9FNa** [comment]
> I'm on arch linux, i ran the command in the readme (`git clone https://github.com/Steamopollys/Steamodded.git && cd Steamodded && python3 steamodded_injector.py $($HOME/.local/share/Steam/steamapps/common/Balatro/Balatro.exe | head -n 1) $HOME/.local/share/Steam/steamapps/common/Balatro/Balatro.exe`) but got that error from the steamodded_injector.py. I changed 7zz on line 155 to 7z and it worked properly. I do have 7-zip installed on my distro. ![image](https://private-user-images.githubusercontent.com/37221707/316348140-9c518329-f898-40fe-8256-34c034760c01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTE0NjQsIm5iZiI6MTcxMjE1MTE2NCwicGF0aCI6Ii8zNzIyMTcwNy8zMTYzNDgxNDAtOWM1MTgzMjktZjg5OC00MGZlLTgyNTYtMzRjMDM0NzYwYzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDEzMzI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MWRkMWVlMzlmYWE1OTgxOTZkMGY2OTkzYTM3MGIyMGYwYTU0ZTliZDJmOWMzY2E3OGE0MzllNTVhZWE4MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YMoHZ0lL_PfFN4x70v22OnJEtGASgiv-Rmp8LMIaP_o)

Confirmed this works for Steam Deck.
![Screenshot_20240403_142932](https://github.com/Steamopollys/Steamodded/assets/63041557/cc993734-c41a-4d7e-82d4-99b544402c0b)

**Comment by deafwired** [comment]
From what I can tell looking at [p7zip's](https://github.com/p7zip-project/p7zip) github, the command is 7z not 7zz. (here is a screenshot of their [usage](https://github.com/p7zip-project/p7zip?tab=readme-ov-file#usage)) 
![image](https://github.com/Steamopollys/Steamodded/assets/37221707/f5cd051d-c522-408d-9118-ca4288f2b005)
I think that replacing 7zz with 7z will fix this problem on linux.

**Comment by Richard-Abel2007** [comment]
I am running linux mint and had the same problem so I changed 7zz to 7z and then got this.
bash: /home/****/.local/share/Steam/steamapps/common/Balatro/Balatro.exe: No such file or directory     
Starting the process...
/tmp/tmpfsci1fzm
Downloading and extracting 7-Zip suite...
SFX Archive received: /home/****/.local/share/Steam/steamapps/common/Balatro/Balatro.exe
/tmp/tmpedbdyist

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (806C1),ASM,AES-NI)

Scanning the drive for archives:
                                                                    
ERROR: No such file or directory
/home/****/.local/share/Steam/steamapps/common/Balatro/Balatro.exe



System ERROR:
Unknown error -2147024894
Traceback (most recent call last):
  File "/home/****/Steamodded/steamodded_injector.py", line 178, in <module>
    subprocess.run([command, "x", f"-o{temp_dir.name}", sfx_archive_path], check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['7z', 'x', '-o/tmp/tmpedbdyist', '/home/****/.local/share/Steam/steamapps/common/Balatro/Balatro.exe']' returned non-zero exit status 2.
the  **** is host name

**Comment by Jammintk** [comment]
I can confirm that this issue happened on Manjaro (with p7zip) and the fix above helped.

For those that want a little more guidance, open the folder where you ran the command in the terminal. If you just opened the terminal and pasted the command without navigating to a new folder, you just need to enter the Steamodded folder like this:

`cd ~/Steamodded`

then edit the steamodded_injector.py (I use nano in this example, but any text editor should work.)

`nano steamodded_injector.py`

scroll down until you see the line

`if os.name == 'posix':`

Just a couple lines down you should see a comment about Linux with a line below

`          command = "7zz"`

change the 7zz on this line to 7z, so it looks like this:

`          command = "7z"

then save and close the file (on nano, this is ctrl+x, then y) and re-run the last part of the command again

`python3 steamodded_injector.py $($HOME/.local/share/Steam/steamapps/common/Balatro/Balatro.exe | head -n 1) $HOME/.local/share/Steam/steamapps/common/Balatro/Balatro.exe`

The command should finish successfully now.
