### ISSUE TITLE
ace king queen jack 10 don't count as a straight

### ISSUE THREAD

**Issue by remivamp** [Steamopollys/Steamodded#51]
![20240325233314_1](https://github.com/Steamopollys/Steamodded/assets/16311794/fefb57e8-7ad6-48b4-ac4b-6ce501ae9945)

No extra mods are loaded, only base stuff

**Comment by remivamp** [comment]
Update, nothing counts as a straight

**Comment by Steamopollys** [comment]
Hey, what version do you use ?

**Comment by remivamp** [comment]
update again, as long as a straight uses ace, it doesn't count but i just tested a 9 10 J Q K straight and it works

**Comment by Aurelius7309** [comment]
Already well aware of this, and it's really just a dumb off-by-one error I made when trying to prevent infinite loops during hand calculation. Pushing a fix shortly
