### ISSUE TITLE
Github actions running in forks

### ISSUE THREAD

**Issue by jubnl** [Steamopollys/Steamodded#64]
Hello, the github actions are running in the forks too, could you please add an if condition that checks for the repo owner ?

```.yml
jobs:
  some-job:
    if: github.repository_owner == 'Steamopollys'
...
```
solution found here : https://github.com/orgs/community/discussions/26409#discussioncomment-3251822

**Comment by Steamopollys** [comment]
Hello, it was merged to help for a release but it's still not ready. I will had this rule to avoid it running where it's not supposed to 👍

**Comment by Steamopollys** [comment]
Done!

**Comment by jubnl** [comment]
Thanks !
