### ISSUE TITLE
Game crash when a custom voucher has a defined redeem function + you start a run with Nebula or Zodiac Deck

### ISSUE THREAD

**Issue by GauntletGames-2086** [Steamopollys/Steamodded#65]
Self explanatory. Found it when accidentally starting a run with Nebula Deck instead of Ghost Deck. 
Note that everything works fine if you load a base game deck that isn't Nebula or Zodiac. 
Code used to brute force the error: 

	function SMODS.INIT.TestMod()
		local voucher_def = {
			test_voucher_1 = {
				["name"] = "Test Voucher",
				["text"] = {
					"Testing an error in Steamodded"
				}
			}
		}

		-- SMODS.Deck:new(name, slug, config, spritePos, loc_txt, unlocked, discovered)
		local test_voucher_1 = SMODS.Voucher:new(
			"Test Voucher", --name
			"test_voucher_1", --slug
			{}, --config
			{x = 4, y = 2}, --spritePos
			voucher_def.test_voucher_1, --loc_txt
			10, --cost
			true, --unlocked
			true, --discovered
			true, --available
			{}, --requires
			nil --atlas
		)

		test_voucher_1:register()

		function SMODS.Vouchers.v_test_voucher_1.redeem(center)
			G.GAME.spectral_rate = 2
		end
	end

**Comment by GauntletGames-2086** [comment]
Forgot to take an image of the exact error, so here it is
![image](https://github.com/Steamopollys/Steamodded/assets/73145114/f59c92ea-c8da-407b-bfbc-da99e4fc39e4)

**Comment by Aurelius7309** [comment]
Thanks for your report, this should be fixed in the upcoming new release.
