### ISSUE TITLE
Code Injection

### ISSUE THREAD

**Issue by Jazriel** [Steamopollys/Steamodded#67]
I have been digging in the code and can't find a way to inject code into custom parts of the code, does this functionality exists?

I'm trying to build a mod which needs to inject some code into the main game loop and I'm not finding the way, for now I think I have a workaround.

**Comment by jubnl** [comment]
This functionality exists through lovely injector!
You can find how to use it there : https://github.com/ethangreen-dev/lovely-injector?tab=readme-ov-file#patches

**Comment by Steamopollys** [comment]
Hello,

I still have a wrapper for this in preparation. It's not released yet and will probably not cover all options from lovely (and will cover other). I will update this ticket when it's released.

**Comment by Jazriel** [comment]
@Steamopollys if there is any way to contribute to speed this up I'm willing to try to help!

I'd like to get this going to have a more universal modloader, as it could support the same events balamod does and have injection capabilities, that way it'd be compatible with all the mods created that use a modloader
