### ISSUE TITLE
Cannot load mod files

### ISSUE THREAD

**Issue by huadaxiaa** [Steamopollys/Steamodded#7]
is it right like this? But I cannot load mod files, 

![mod folder](https://github.com/Steamopollys/Steamodded/assets/8764091/508788f6-7a43-4472-ba1e-ddb6de7a8779)
![mod list](https://github.com/Steamopollys/Steamodded/assets/8764091/cfaae57f-50ba-4b21-9648-61a5ffccb4a1)

**Comment by Steamopollys** [comment]
Hello, can you check if your Mod files end of line type is LF ?

If not you can modify it with VSCode or: https://stackoverflow.com/questions/3569997/how-to-find-out-line-endings-in-a-text-file

**Comment by huadaxiaa** [comment]
> Hello, can you check if your Mod files end of line type is LF ?
> 
> If not you can modify it with VSCode or: https://stackoverflow.com/questions/3569997/how-to-find-out-line-endings-in-a-text-file

Thank you, it works!
