### ISSUE TITLE
Allow mods to be loaded from external sources

### ISSUE THREAD

**Issue by WilsontheWolf** [Steamopollys/Steamodded#76]
It would be nice if steamodded could provide it's API to mods that aren't loaded through steamodded itself. For example, it would be handy for many mods to use lovely for patching stuff, but using steamodded for adding jokers. One thing I notice is lovely lets you add new modules, so you could use this to let other mods import steamodded and then use steamodded from the import.

**Comment by Steamopollys** [comment]
Hey, what would be a convenient way for you to request it in your code ?
