### ISSUE TITLE
Linux support ?

### ISSUE THREAD

**Issue by Enderteck** [Steamopollys/Steamodded#78]
Can this support either the Balatro.love (renamed from .exe) or a Linux binary made with my guide ? https://steamcommunity.com/sharedfiles/filedetails/?id=3220403989

It's a work in progress but allows you to run the game as ac Linux executable and even through native Wayland (you'll be able to when I'll be done making the guide)

**Comment by Steamopollys** [comment]
Hello,

Did you test the mac installation process ? It might be working more or less the same since you use a .love file.

**Comment by Enderteck** [comment]
I get this issue hen I try the Mac command:

Traceback (most recent call last):
  File "/home/user/Steamodded/steamodded_injector.py", line 178, in <module>
    subprocess.run([command, "x", f"-o{temp_dir.name}", sfx_archive_path], check=True)
  File "/usr/lib64/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '7zz'

**Comment by Enderteck** [comment]
Does that mean I have to merge the Balatro.love zip after it's merged with the love executable or will it be able to mod the Balatro Linux executable ?

**Comment by Steamopollys** [comment]
Can you try to replace it by 7z and not 7zz ?

**Comment by Spiricore** [comment]
I'm having the same error with my install on my Steam Deck.

Traceback (most recent call last):
File "/home/user/Steamodded/steamodded_injector.py", line 178, in
subprocess.run([command, "x", f"-o{temp_dir.name}", sfx_archive_path], check=True)
File "/usr/lib64/python3.12/subprocess.py", line 548, in run
with Popen(*popenargs, **kwargs) as process:
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.12/subprocess.py", line 1026, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib64/python3.12/subprocess.py", line 1953, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '7zz'

Changing all entries of 7zz to 7z ip steamodded_injector.py yielded the same result.

**Comment by antipatico** [comment]
Changing `7zz` to `7za` fixed it on my system (Debian)
