### ISSUE TITLE
beta issue?

### ISSUE THREAD

**Issue by BalatroUser69** [Steamopollys/Steamodded#79]
I turned on the new beta for balatro and played for a bit but when I turned it back to the normal version than steamodded won't show and I've tried reinstalling balatro and it won't work.

**Comment by Steamopollys** [comment]
Hello,

If you installed Steamodded without lovely and with the injector it's normal. The modloader is injected into the game file. If they are updated you have to re do the installation. By switching to the experimental branch, that's exactly what happened.

**Comment by BalatroUser69** [comment]
TY helped a lot!
