### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by The-foxxy** [Steamopollys/Steamodded#80]
both PS  injector and normal one have viruses with them

**Comment by oxiclean4x** [comment]
yeah my browser refuses to download .9.7 or .9.8

**Comment by mike4263** [comment]
I bypassed the browser security and it got flagged by Windows Defender as Program:Win32/Contebrew.A!ml

This post describes similar behavior - https://github.com/danielkrupinski/Osiris/issues/2786 .  Its probably safe to ignore this...

**Comment by Aurelius7309** [comment]
It's safe to ignore any antivirus warnings, but the executable injector is no longer recommended at this point. A switch to using Lovely as the main and only way of installation, which is safer, does not modify the game files directly and need not be re-injected when the game updates. More detailed information on this will be added to this repository soon. In the meantime, please refer to either this [text guide](https://canary.discord.com/channels/1116389027176787968/1217867725532041369/1217867725532041369) on Discord, or this [video guide](https://youtu.be/62DAxTg4fqw) to install Steamodded with Lovely.
