### ISSUE TITLE
The Steammodded download keeps auto deleting itself

### ISSUE THREAD

**Issue by Anoticx** [Steamopollys/Steamodded#85]
When i try to download[steamodded_injector.exe](https://github.com/Steamopollys/Steamodded/releases/download/0.9.8/steamodded_injector.exe) it auto deletes it self. Can yall help me?

**Comment by Aurelius7309** [comment]
The injector has an antivirus issue. You should install Steamodded using lovely instead, guides for this are linked in https://github.com/Steamopollys/Steamodded/issues/80#issuecomment-2067716391, but clearer instructions will be added to this site as well in the near future. Alternatively you would need to temporarily disable your antivirus program.
