### ISSUE TITLE
MoreSpeeds crashing when leaving settings screen

### ISSUE THREAD

**Issue by surskitt** [Steamopollys/Steamodded#89]
When I have MoreSpeeds in my Mods folder the game crashes when I open and close the settings screen. It happens whether I change any settings or not.

![b6](https://github.com/Steamopollys/Steamodded/assets/1909963/562c348b-2c4a-477e-8b9d-4d56879fb6a3)

The crashes go away once the mod is removed.

I'm using SteamModded 0.9.8 at the moment, but it was still happening on the recent main commits. I did try the newest one right before creating this issue, but it's currently causing some other crashes.

I think this started happening on one of the later experimental patches, the first few seemed to be fine. Crash still happens on the current stable balatro version.

**Comment by Infarcactus** [comment]
Why are you writing this here ? 
The mod causes problems not Steamodded !

**Comment by surskitt** [comment]
> Why are you writing this here ? The mod causes problems not Steamodded !

The mod is part of this repo...

**Comment by eszoke** [comment]
So not a true fix, but it's definitely some part of the Custom Speed box that is causing the issue. If you comment out Line 71 on the Lua file the box doesn't appear and it no longer crashes. The new speeds in the top selector (like 3x) still work so if you're only using those this fix will work.

**Comment by surskitt** [comment]
I wasn't using the custom speed box, so I've commented it (and line 70) and it no longer crashes. Thanks a lot!

**Comment by Infarcactus** [comment]
> I wasn't using the custom speed box, so I've commented it (and line 70) and it no longer crashes. Thanks a lot!

It's not because it's used as an example mod that the author of the mod is developping this app, the mods also may be out of date. They only serve as demonstration and not use. 
If you get a problem like this I would strongly recommend directly asking the mod author and checking if you have the latest version.

**Comment by eszoke** [comment]
> > I wasn't using the custom speed box, so I've commented it (and line 70) and it no longer crashes. Thanks a lot!
> 
> It's not because it's used as an example mod that the author of Steamodded is developping this mod, the mods also may be out of date. They only serve as demonstration and not use. 
> If you get a problem like this I would strongly recommend directly asking the mod author and checking if you have the latest version.

Isn't this the only place where those examples mods exist though? Since they all have Steamo as the mod author too. True they're might be updated versions but not sure what a better place to ask about it would be.
