### ISSUE TITLE
Issue with localization on startup

### ISSUE THREAD

**Issue by BeningnGamer** [Steamopollys/Steamodded#95]
Using steamdeck had issue with 7zip, but the 7z fix helped. Now my startup w/ no mods btw gives me this error:
Oops! The game crashed:
main.lua:7101: attempt to concatenate field 'dir' (a nil value)

Additional Context:
Balatro Version: 1.0.1f-FULL
Modded Version: 1.0.0-ALPHA-STEAMODDED
Love2D Version: 11.5.0
Steamodded Mods:

Stack Traceback
===============
(3) Lua method 'inject' at file 'main.lua:7101'
Local variables:
 self = table: 0x0c8a0be8  {path:tag_error.png, loc_txt:table: 0x0c8a0e80, py:34, process_loc_text:function: 0x0c8a04e8 (more...)}
 file_path = string: "tag_error.png"
 (*temporary) = nil
 (*temporary) = string: "assets/2x/tag_error.png"
 (*temporary) = string: "2"
 (*temporary) = string: "x/"
 (*temporary) = string: "tag_error.png"
 (*temporary) = string: "tag_error_en-us"
 (*temporary) = string: "attempt to concatenate field 'dir' (a nil value)"
(4) Lua method 'injector' at file 'main.lua:6974'
Local variables:
 self = table: 0x0c8a0b68  {required_params:table: 0x0c8a0a98, set:Sprite, children:table: 0x0c8a0bc0 (more...)}
 o = table: 0x0c8a0be8  {path:tag_error.png, loc_txt:table: 0x0c8a0e80, py:34, process_loc_text:function: 0x0c8a04e8 (more...)}
 (for generator) = C function: builtin#6
 (for state) = table: 0x0c8a08e0  {1:tag_error}
 (for control) = number: 1
 i = number: 1
 key = string: "tag_error"
(5) Lua field 'injectObjects' at file 'main.lua:7014'
Local variables:
 class = table: 0x0c8a0b68  {required_params:table: 0x0c8a0a98, set:Sprite, children:table: 0x0c8a0bc0 (more...)}
(6) Lua field 'injectObjects' at file 'main.lua:7016'
Local variables:
 class = table: 0x0c89fcd0  {process_loc_text:function: 0x0c89ff08, children:table: 0x0c89fd98, __call:function: 0x0c89fea8 (more...)}
 (for generator) = C function: builtin#6
 (for state) = table: 0x0c89fd98  {1:table: 0x0c8a04c0, 2:table: 0x0c8a0840, 3:table: 0x0c8a0b68, 4:table: 0x0c8a1880 (more...)}
 (for control) = number: 3
 _ = number: 3
 subclass = table: 0x0c8a0b68  {required_params:table: 0x0c8a0a98, set:Sprite, children:table: 0x0c8a0bc0 (more...)}
(7) Lua field 'injectItems' at file 'main.lua:9229'
(8) Lua global 'initSteamodded' at file 'main.lua:9257'
(9) Lua method 'start_up' at file 'game.lua:209'
Local variables:
 self = table: 0x04350830  {ANIMATION_FPS:10, SPEEDFACTOR:1, F_CRASH_REPORTS:false, keybind_mapping:table: 0x0435af98 (more...)}
 settings = string: "return {[\"version\"]=\"1.0.1f-FULL\",[\"ambient_control\"]={[\"ambientFire1\"]={[\"per\"]=1.1,[\"vol\"]=0,},[\"ambientOrgan1\"]={[\"per\"]=0.7,[\"vol\"]=0,},[\"ambientFire2\"]={[\"per\"]=1.05,[\"vol\"]=0,},[\"ambientFire3\"]={[\"per\"]=1,[\"vol\"]=0,},},[\"QUEUED_CHANGE\"]={},[\"COMP\"]={[\"prev_name\"]=\"\",[\"name\"]=\"\",[\"score\"]=4.7023906104141e+16,},[\"colourblind_option\"]=false,[\"play_button_pos\"]=2,[\"profile\"]=1,[\"crashreports\"]=false,[\"tutorial_progress\"]={[\"hold_parts\"]={},[\"section\"]=\"big_blind\",[\"completed_parts\"]={[\"first_hand_3\"]=true,[\"small_blind\"]=true,[\"big_blind\"]=true,[\"first_hand_4\"]=true,[\"shop_1\"]=true,[\"first_hand_section\"]=true,[\"first_hand_2\"]=true,[\"first_hand\"]=true,},},[\"WINDOW\"]={[\"selected_display\"]=1,[\"display_names\"]={[1]=\"1\",},[\"screenmode\"]=\"Borderless\",[\"DISPLAYS\"]={[1]={[\"screen_res\"]={[\"w\"]=1280,[\"h\"]=800,},[\"screen_resolutions\"]={[\"strings\"]={[1]=\"1280 X 800\",},[\"values\"]={[1]={[\"h\"]=800,[\"w\"]=1280,},},},[\"DPI_scale\"]=1,[\"MONITOR_DIMS\"]={[\"height\"]=800,[\"width\"]=1280,},},},[\"vsync\"]=1,},[\"GRAPHICS\"]={[\"shadows\"]=\"On\",[\"crt\"]=70,[\"texture_scaling\"]=2,[\"bloom\"]=1,},[\"GAMESPEED\"]=4,[\"SOUND\"]={[\"volume\"]=50,[\"music_volume\"]=100,[\"game_sounds_volume\"]=100,},[\"music_control\"]={[\"current_track\"]=\"\",[\"desired_track\"]=\"\",[\"lerp\"]=1,},[\"ACHIEVEMENTS_EARNED\"]={[\"card_discarder\"]=true,[\"_10k\"]=true,[\"retrograde\"]=true,[\"shattered\"]=true,[\"tiny_hands\"]=true,[\"_100000k\"]=true,[\"cartomancy\"]=true,[\"mid_stakes\"]=true,[\"low_stakes\"]=true,[\"card_player\"]=true,[\"ante_upper\"]=true,[\"astronomy\"]=true,[\"rule_bender\"]=true,[\"nest_egg\"]=true,[\"_1000k\"]=true,[\"legendary\"]=true,[\"royale\"]=true,[\"heads_up\"]=true,[\"roi\"]=true,[\"clairvoyance\"]=true,[\"ante_up\"]=true,[\"you_get_what_you_get\"]=true,},[\"tutorial_complete\"]=true,[\"current_setup\"]=\"New Run\",[\"screenshake\"]=50,[\"paused\"]=false,[\"DEMO\"]={[\"win_CTA_shown\"]=true,[\"quit_CTA_shown\"]=true,[\"timed_CTA_shown\"]=true,[\"total_uptime\"]=15.040020424434,},[\"language\"]=\"en-us\",}"
 settings_ver = nil
 new_colour_proto = table: 0x04356c00  {Spades:table: 0x04358760, Hearts:table: 0x043585f0, Diamonds:table: 0x04358688 (more...)}
 sound_files = table: 0x04351898  {1:ambientFire1.ogg, 2:ambientFire2.ogg, 3:ambientFire3.ogg, 4:ambientOrgan1.ogg (more...)}
 shader_files = table: 0x044b9c30  {1:CRT.fs, 2:background.fs, 3:booster.fs, 4:debuff.fs, 5:dissolve.fs, 6:flame.fs (more...)}
(10) Lua field 'load' at file 'main.lua:87'
(11) Lua function '?' at file 'main.lua:34' (best guess)
(12) global C function 'xpcall'
(13) Love2D function at file 'boot.lua:368' (best guess)
Local variables:
 result = boolean: true
 main = nil
(14) global C function 'xpcall'
(15) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])
I'm completely lost

**Comment by Aurelius7309** [comment]
The injector will no longer work with the alpha 1.0.0 version of Steamodded, which is what it seems you're using here. I'm sorry that the installation instructions are currently unclear - they will be completely redone before the release of that version. I will add a temporary solution that works for 0.9.8 in the meantime though

**Comment by BeningnGamer** [comment]
> The injector will no longer work with the alpha 1.0.0 version of Steamodded, which is what it seems you're using here. I'm sorry that the installation instructions are currently unclear - they will be completely redone before the release of that version. I will add a temporary solution that works for 0.9.8 in the meantime though

Thanks so much for the help and making the software. You're a true king/queen

**Comment by Aurelius7309** [comment]
Thank you!
