### ISSUE TITLE
Stone card is not considered a face card with Pareidolia

### ISSUE THREAD

**Issue by WYXkk** [Steamopollys/Steamodded#96]
Thus can't activate Reserved Parking, Canio, Business Card, etc and don't break Ride the Bus.

This issue doesn't happen when I remove Steamodded.

**Comment by WYXkk** [comment]
Tried looking at source but found nothing. Is this already fixed in the developing new version by completely rewrite?

**Comment by Aurelius7309** [comment]
This is fixed for the upcoming major version.
