### ISSUE TITLE
can't find mod file

### ISSUE THREAD

**Issue by staley2** [Steamopollys/Steamodded#98]
I am unable to locate the mod file and could use some help looking for it.

**Comment by Aurelius7309** [comment]
I'm not sure what you mean?

**Comment by staley2** [comment]
when you first inject Balatro with the steam mod injector, it prompts you to open a mod file where you can drag and drop downloaded mods into the file. the mod I downloaded got an update and I'm trying to find the mod file again to no avail. I'm asking if there is any way to access the mod file that I don't know about.

**Comment by Aurelius7309** [comment]
On Windows, the Mods folder is located at C:\Users\<user>\AppData\Roaming\Balatro

**Comment by staley2** [comment]
ok, thank you for the help.
